# Changes here will be overwritten by Copier
_commit: v2.0.5
_src_path: gh:lincc-frameworks/python-project-template
author_email: etienne.russeil@astro.su.se
author_name: Etienne Russeil
create_example_module: false
custom_install: true
enforce_style: []
failure_notification: []
include_benchmarks: false
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: mvsr
project_license: MIT
project_name: mvsr
project_organization: erusseil
python_versions:
- '3.9'
- '3.10'
- '3.11'
- '3.12'
- '3.13'
